### ISSUE TITLE
Missed manager

### ISSUE THREAD

**Issue by zooeywm** [TD-Sky/dotfiles#1]
https://github.com/TD-Sky/dotfiles/blob/495acd53bae9640ae80a7562f861e550e2c9662a/Templates/apps.toml#L13
https://github.com/TD-Sky/dotfiles/blob/495acd53bae9640ae80a7562f861e550e2c9662a/Templates/apps.toml#L274

When I run `iwant Templates/app.toml`, it returns with
```
error: target not fuond: ventoy-bin
error: target not fuond: dida365
```
After specifying it to 

```
ventoy = { manager = "paru", packages = ["ventoy-bin"], description = "制作镜像盘" } 
dida365 = { manager = "paru", description = "滴答清单" }
 ``` 

It turns to work fine

**Comment by zooeywm** [comment]
https://github.com/TD-Sky/dotfiles/blob/495acd53bae9640ae80a7562f861e550e2c9662a/Templates/apps.toml#L22
https://github.com/TD-Sky/dotfiles/blob/495acd53bae9640ae80a7562f861e550e2c9662a/Templates/apps.toml#L40

And may need to add npm and nodejs, because some item depend on them or use them

**Comment by zooeywm** [comment]
And tree-sitter-cli via npm for neovim

`tree-sitter-cli = { manager = "npm", description = "tree sitter cli" }`

**Comment by TD-Sky** [comment]
> And tree-sitter-cli via npm for neovim
> 
> `tree-sitter-cli = { manager = "npm", description = "tree sitter cli" }`

You can install `tree-sitter-cli` which is in **extra** repo via pacman.
